### ISSUE TITLE
open_restart always includes time in state if a coupler.res file exists

### ISSUE THREAD

**Issue by spencerkclark** [VulcanClimateModeling/fv3gfs-util#38] opened 2021-01-14 15:40 UTC
Currently if a `coupler.res` file exists in the directory provided, `fv3gfs.util.open_restart` will always return `"time"` in the state, regardless of whether it is requested in the `only_names` or not.  This leads to issues in the nudging workflow.  We could work around this there, but I thought it might make sense to first ask whether or not this is the intended behavior.  Naively I would assume if `"time"` is not in the `only_names` it should not be returned in the state.

```python
>>> import fv3gfs.util
>>> dummy_comm = fv3gfs.util.testing.DummyComm(0, 6, {})
>>> partitioner = fv3gfs.util.CubedSpherePartitioner(fv3gfs.util.TilePartitioner([1, 1]))
>>> communicator = fv3gfs.util.CubedSphereCommunicator(dummy_comm, partitioner)
>>> only_names = ["air_temperature"]
>>> directory = "gs://vcm-ml-raw-flexible-retention/2021-01-04-1-year-C384-FV3GFS-simulations/unperturbed/C384-to-C48-restart-files/20170801.001500"
>>> list(fv3gfs.util.open_restart(directory, communicator, label="20170801.001500", only_names=only_names).keys())
['air_temperature', 'time']
```

**Comment by mcgibbon** [comment] 2021-01-14 17:18
Not sure whether it was intended or not. The problem is "state" was originally supposed to mean "a dictionary with a time key whose value is time-like and other keys whose values are Quantity", but several routines don't require the time key, so we've also used "states" which do not have a time.

I'd say this is a bug which should be fixed. If we later change to have a State class that e.g. has `state["air_temperature"]` and `state.time` we can change the behavior back at that time.

**Comment by spencerkclark** [comment] 2021-01-14 19:33
Thanks for your thoughts @mcgibbon -- I made a short PR with a fix.

**Closed** 2021-01-14 20:00 UTC
